# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.ssh.insert_key = false

  config.vm.define "docker" do |docker|
    docker.vm.box="ivelin1936/VCentos"
    docker.vm.hostname = "docker.hw.tf"
    docker.vm.network "private_network", ip: "192.168.56.11"
    docker.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
    docker.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    docker.vm.provision "shell", path: "addons_centos.sh"
    docker.vm.provision "shell", path: "host_config.sh"
    docker.vm.provision "shell", path: "centos_firewall_setup.sh"
    docker.vm.provision "shell", path: "docker-setup_centos.sh"
    docker.vm.provision "shell", path: "application_config.sh"
    docker.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.name = "CENTOS_DO"
    end
  end
  
end
