---
- hosts: webservers
  become: true

  vars_files:
    - vars/default.yml

  tasks:
    - name: Updating the repo
      apt:
         update_cache: yes
         state: latest
         force_apt_get: yes

    - name: Installation PHP 7.4
      apt:
         name: php,php-mysql,libapache2-mod-php,php-cli
         state: present

    - name: Install Apache HTTP Server
      apt:
         name: apache2
         update_cache: yes
         state: latest

    - name: Start Apache HTTP Server and Enable it
      service:
         name: apache2
         state: started
         enabled: true

    - name: Delete content & directory
      file:
         state: absent
         path: /var/www/html/index.html

    - name: Deploy web page
      template:
         src: "/home/vagrant/web/index.php"
         dest: "/var/www/html/index.php"

    - name: Deploy web resources
      copy:
         src: "/home/vagrant/web/bulgaria-map.png"
         dest: "/var/www/html/"

    - name: Modify web file/s permissions (insecure permissions to index.php)
      file:
         path: /var/www/html/index.php
         owner: root
         group: root
         mode: '1777'
      notify: Restart Apache

    #- name: "UFW - Allow HTTP on port {{ http_port }}"
      #ufw:
        #rule: allow
        #port: "{{ http_port }}"
        #proto: tcp

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

- hosts: dbservers
  gather_facts: true
  become: true

  vars_files:
    - vars/default.yml

  tasks:
    - name: Start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
      become: yes

    - name: Enable Firewall ports
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      loop:
        - 3306/tcp

    - name: Reload service firewalld
      systemd:
        name: firewalld
        state: reloaded

    - name: Install MariaDB
      yum:
         name:
           - mariadb-server
           - python3-PyMySQL
         state: latest

    - name: (DATABASE) Make sure the MariaDB service is started and enabled at boot
      service:
        name: mariadb
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"

    - name: (DATABASE) Allow remote hosts to connect
      lineinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf
        state: present
        insertafter: '^\[mysqld\]'
        line: 'bind-address            = {{ db_server_bind_address }}'

    - name: Start mariadb
      service:
        name: mariadb
        enabled: true
        state: started

    - name: Manage DB users
      mysql_user:
        login_user: "{{ web_user }}"
        login_password: "{{ web_user_password }}"
        user: root
        check_implicit_admin: true
        password: ""
        priv: '*.*:ALL,GRANT'
        host: "{{ db_host }}"

    - name: Save root credentials into .my.cnf
      template:
        src: root_cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: '0600'

    - name: Copy DB backup
      copy:
         src: "/home/vagrant/db/db_setup.sql"
         dest: "/home/vagrant/db/"

    - name: Ensure '{{ db_name }}' database exists! If no - Import it (mysql -u <username> -p <password> < hostname.sql)
      mysql_db:
         name: "{{ db_name }}"
         state: present
      notify: Import database

  handlers:
    - name: Import database
      mysql_db:
        state: import
        name: all
        target: /home/vagrant/db/db_setup.sql
