# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "server" do |server|
    server.vm.box="ivelin1936/VCentos"
    server.vm.hostname = "centos.m7.se"
    server.vm.provider :virtualbox do |vb|
        vb.name = "COSM7_SERVER"
        vb.gui = false
        vb.memory = 4096
        vb.cpus = 2
    end
    server.vm.network "private_network", ip: "192.168.56.11"
    server.vm.synced_folder "elk", "/home/vagrant/elk"
    server.vm.provision "shell", path: "add_hosts.sh"
    server.vm.provision "shell", path: "addons_centos.sh"
    server.vm.provision "shell", path: "centos_firewall_setup_elk.sh"
    server.vm.provision "shell", path: "docker-setup_centos.sh"
    server.vm.provision "shell", path: "deploy_elk.sh"
  end

  config.vm.define "ccentos" do |ccentos|
    ccentos.vm.box="ivelin1936/VCentos"
    ccentos.vm.hostname = "centos.m7.fc"
    ccentos.vm.provider :virtualbox do |vb|
        vb.name = "COSM7_CLIENT"
        vb.gui = false
        vb.memory = 512
        vb.cpus = 1
    end
    ccentos.vm.network "private_network", ip: "192.168.56.12"
    ccentos.vm.synced_folder "beats", "/home/vagrant/beats"
    ccentos.vm.provision "shell", path: "add_hosts.sh"
    ccentos.vm.provision "shell", path: "addons_centos.sh"
    ccentos.vm.provision "shell", path: "centos_firewall_setup_client.sh"
    ccentos.vm.provision "shell", path: "install_beats.sh", :args => "centos metricbeat"
  end

  config.vm.define "cubuntu" do |cubuntu|
    cubuntu.vm.box="ivelin1936/VUbuntu-20-04-server"
    cubuntu.vm.hostname = "ubuntu.m7.sc"
    cubuntu.vm.provider :virtualbox do |vb|
        vb.name = "UM7_CLIENT"
        vb.gui = false
        vb.memory = 512
        vb.cpus = 1
    end
    cubuntu.vm.network "private_network", ip: "192.168.56.13"
    cubuntu.vm.synced_folder "beats", "/home/vagrant/beats"
	cubuntu.vm.provision "shell", path: "add_hosts.sh"
    cubuntu.vm.provision "shell", path: "addons_ubuntu.sh"
    cubuntu.vm.provision "shell", path: "install_beats.sh", :args => "ubuntu metricbeat"
  end

end
