# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "server" do |server|
    server.vm.box="ivelin1936/VCentos"
    server.vm.hostname = "centos.m7.se"
    server.vm.provider :virtualbox do |vb|
        vb.name = "COSM7_SERVER"
        vb.gui = false
        vb.memory = 4096
        vb.cpus = 2
    end
    server.vm.network "private_network", ip: "192.168.56.11"
    server.vm.synced_folder "share", "/home/vagrant/share"
    server.vm.provision "shell", path: "add_hosts.sh"
    server.vm.provision "shell", path: "addons_centos.sh"
    server.vm.provision "shell", path: "centos_firewall_setup_elk.sh"
    server.vm.provision "shell", path: "docker-setup_centos.sh"
  end

  config.vm.define "fclient" do |fclient|
    fclient.vm.box="ivelin1936/VCentos"
    fclient.vm.hostname = "centos.m7.fc"
    fclient.vm.provider :virtualbox do |vb|
        vb.name = "COSM7_FCLIENT"
        vb.gui = false
        vb.memory = 512
        vb.cpus = 1
    end
    fclient.vm.network "private_network", ip: "192.168.56.12"
    fclient.vm.provision "shell", path: "add_hosts.sh"
    fclient.vm.provision "shell", path: "addons_centos.sh"
    fclient.vm.provision "shell", path: "centos_firewall_setup_client.sh"
    fclient.vm.provision "shell", path: "metricbeat_centos_setup.sh"
  end

  config.vm.define "sclient" do |sclient|
    sclient.vm.box="ivelin1936/VUbuntu-20-04-server"
    sclient.vm.hostname = "ubuntu.m7.sc"
    sclient.vm.provider :virtualbox do |vb|
        vb.name = "COSM7_SCLIENT"
        vb.gui = false
        vb.memory = 512
        vb.cpus = 1
    end
    sclient.vm.network "private_network", ip: "192.168.56.13"
	sclient.vm.provision "shell", path: "add_hosts.sh"
    sclient.vm.provision "shell", path: "addons_ubuntu.sh"
    sclient.vm.provision "shell", path: "metricbeat_ubuntu_setup.sh"
  end

end
