    - name: Manage DB users
      mysql_user:
        login_user: "{{ web_user }}"
        login_password: "{{ web_user_password }}"
        user: root
        check_implicit_admin: true
        password: ""
        priv: '*.*:ALL,GRANT'
        host: "{{ db_host }}"

    - name: Save root credentials into .my.cnf
      template:
        src: templates/root_cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: '0600'

    - name: Copy DB backup
      copy:
         src: "/home/vagrant/db/db_setup.sql"
         dest: "/home/vagrant/db/"

    - name: Ensure '{{ db_name }}' database exists! If no - Import it (mysql -u <username> -p <password> < hostname.sql)
      mysql_db:
         name: "{{ db_name }}"
         state: present
      notify: Import database
