# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "ans" do |ans|
    ans.vm.box = "ivelin1936/VCentos"
    ans.vm.hostname = "ans.do2.hw"
    ans.vm.network "private_network", ip: "192.168.56.10"
    ans.vm.provider :virtualbox do |vb|
        vb.name = "ANS"
        vb.gui = false
        vb.memory = 1024
        vb.cpus = 1
    end
    ans.vm.synced_folder "share/", "/home/vagrant"
    ans.vm.provision "shell", path: "host_config.sh"
    ans.vm.provision "shell", path: "centos_addons.sh"
    ans.vm.provision "shell", path: "ansible_setup_centos.sh"
    ans.vm.provision "shell", path: "ans_hosts_setup.sh"
  end

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/debian-11"
    web.vm.hostname = "web.do2.hw"
    web.vm.network "private_network", ip: "192.168.56.11"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provider :virtualbox do |vb|
        vb.name = "WEB"
        vb.gui = false
        vb.memory = 1024
        vb.cpus = 1
    end
    web.vm.provision "shell", path: "host_config.sh"
    web.vm.provision "shell", path: "debian_addons.sh"
  end
  
  config.vm.define "db" do |db|
    db.vm.box = "ivelin1936/VCentos"
    db.vm.hostname = "db.do2.hw"
    db.vm.network "private_network", ip: "192.168.56.12"
    db.vm.provider :virtualbox do |vb|
        vb.name = "DB"
        vb.gui = false
        vb.memory = 1024
        vb.cpus = 1
    end
    db.vm.provision "shell", path: "host_config.sh"
    db.vm.provision "shell", path: "centos_addons.sh"
  end
 
end
